"""add punch_type column

Revision ID: 1f0501f1da74
Revises: 6554ed244684
Create Date: 2026-05-06 13:46:21.323018

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f0501f1da74"
down_revision: str | Sequence[str] | None = "6554ed244684"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("punch_event", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "punch_type",
                sa.Enum("JAB", "CROSS", "HOOK", "UPPERCUT", name="punchtypeenum"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("punch_event", schema=None) as batch_op:
        batch_op.drop_column("punch_type")

    # ### end Alembic commands ###
