"""baseline phase 1 schema

Revision ID: 6554ed244684
Revises:
Create Date: 2026-05-06 13:30:57.982479

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6554ed244684"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fighter",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("nickname", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("nationality", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
        sa.Column("sex", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.Column(
            "stance", sa.Enum("ORTHODOX", "SOUTHPAW", "SWITCH", name="stance"), nullable=False
        ),
        sa.Column("dominant_hand", sa.Enum("LEFT", "RIGHT", name="handenum"), nullable=True),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("reach_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("shoulder_width_cm", sa.Float(), nullable=True),
        sa.Column(
            "skill_level",
            sa.Enum(
                "RECREATIONAL",
                "AMATEUR_NOVICE",
                "AMATEUR_OPEN",
                "AMATEUR_ELITE",
                "SEMI_PRO",
                "PROFESSIONAL",
                "COACH",
                name="skilllevel",
            ),
            nullable=True,
        ),
        sa.Column("weight_class", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("years_training", sa.Integer(), nullable=True),
        sa.Column("gym", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("trainer", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("record_wins", sa.Integer(), nullable=False),
        sa.Column("record_losses", sa.Integer(), nullable=False),
        sa.Column("record_draws", sa.Integer(), nullable=False),
        sa.Column("record_kos", sa.Integer(), nullable=False),
        sa.Column("boxrec_id", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("usa_boxing_id", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fighter", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fighter_name"), ["name"], unique=False)

    op.create_table(
        "session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fighter_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "LIVE_WEBCAM",
                "UPLOADED_VIDEO",
                "LIVE_IPHONE",
                "POLAR_H10_ONLY",
                "HRV_REPLAY",
                name="sessionsourceenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "CAPTURING", "PROCESSING", "COMPLETED", "FAILED", name="sessionstatus"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("video_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pose_parquet_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("failure_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fighter_id"],
            ["fighter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_fighter_id"), ["fighter_id"], unique=False)

    op.create_table(
        "weigh_in",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fighter_id", sa.Uuid(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fighter_id"],
            ["fighter.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("weigh_in", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_weigh_in_fighter_id"), ["fighter_id"], unique=False)

    op.create_table(
        "hr_sample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("t_ms", sa.Float(), nullable=False),
        sa.Column("rr_ms", sa.Float(), nullable=False),
        sa.Column("hr_bpm", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hr_sample", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hr_sample_session_id"), ["session_id"], unique=False)

    op.create_table(
        "punch_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("t_ms", sa.Float(), nullable=False),
        sa.Column("hand", sa.Enum("LEFT", "RIGHT", name="handenum"), nullable=False),
        sa.Column("lead_or_rear", sa.Enum("LEAD", "REAR", name="leadorrearenum"), nullable=True),
        sa.Column("velocity_ms", sa.Float(), nullable=False),
        sa.Column(
            "velocity_source",
            sa.Enum("WORLD", "IMAGE_HEURISTIC", name="velocitysourceenum"),
            nullable=False,
        ),
        sa.Column(
            "detected_by",
            sa.Enum("HEURISTIC", "LSTM_V1", name="detectionsourceenum"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("punch_event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_punch_event_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("punch_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_punch_event_session_id"))

    op.drop_table("punch_event")
    with op.batch_alter_table("hr_sample", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hr_sample_session_id"))

    op.drop_table("hr_sample")
    with op.batch_alter_table("weigh_in", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weigh_in_fighter_id"))

    op.drop_table("weigh_in")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_fighter_id"))

    op.drop_table("session")
    with op.batch_alter_table("fighter", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fighter_name"))

    op.drop_table("fighter")
    # ### end Alembic commands ###
